import aiofiles
from pathlib import Path
from typing import List, Dict
from backend.config import settings


class KnowledgeBase:
    def __init__(self, base_path: str = None):
        self.base_path = Path(base_path or settings.knowledge_base_chunks)
        self.summary_file = Path(settings.knowledge_base_file_summary)
    
    async def get_file_summary(self) -> str:
        """
        Get knowledge base file summary
        
        The summary file needs to be generated by an independent script:
        Knowledge-Base-File-Summary/generate.py
        
        If the summary file does not exist, return a prompt message
        """
        if self.summary_file.exists():
            async with aiofiles.open(self.summary_file, 'r', encoding='utf-8') as f:
                return await f.read()
        
        return (
            "⚠️ Knowledge Base Summary file not found.\n\n"
            "Please generate it first by running:\n"
            "bash scripts/generate-summary.sh\n"
            "or\n"
            "python Knowledge-Base-File-Summary/generate.py --strict\n\n"
            f"Expected file path: {self.summary_file}"
        )
    
    async def retrieve_files(self, file_paths: List[str]) -> str:
        if not file_paths:
            raise ValueError("file_paths cannot be empty")
        if len(file_paths) > settings.max_retrieve_paths:
            raise ValueError(f"Too many paths requested: {len(file_paths)} > {settings.max_retrieve_paths}")

        results = []
        retrieved_files = 0
        total_chars = 0

        for file_path in file_paths:
            if file_path == "/":
                if not settings.allow_full_retrieval:
                    raise ValueError("Full retrieval ('/') is disabled by server policy")
                md_files = sorted(self.base_path.rglob("*.md"))
            else:
                target_path = self._resolve_safe_path(file_path)

                if target_path.is_dir():
                    md_files = sorted(target_path.rglob("*.md"))
                elif target_path.is_file():
                    if target_path.suffix.lower() != ".md":
                        raise ValueError(f"Only markdown files are allowed: {file_path}")
                    md_files = [target_path]
                else:
                    raise FileNotFoundError(f"Path not found: {file_path}")

            for md_file in md_files:
                if retrieved_files >= settings.max_retrieve_files:
                    raise ValueError(f"Too many files retrieved: {settings.max_retrieve_files} limit reached")

                content = await self._read_file(md_file)
                relative_path = md_file.relative_to(self.base_path)
                rendered_content = f"《{relative_path}》\n\n{content}"

                next_total = total_chars + len(rendered_content)
                if next_total > settings.max_retrieve_chars:
                    raise ValueError(
                        f"Retrieved content exceeds limit: {next_total} > {settings.max_retrieve_chars} characters"
                    )

                results.append(rendered_content)
                retrieved_files += 1
                total_chars = next_total

        final_content = "\n\n==========\n\n".join(results)
        return final_content

    def _resolve_safe_path(self, file_path: str) -> Path:
        requested_path = (file_path or "").strip()
        if not requested_path:
            raise ValueError("Empty path is not allowed")

        candidate = (self.base_path / requested_path.lstrip("/")).resolve()
        base = self.base_path.resolve()
        if candidate != base and base not in candidate.parents:
            raise ValueError(f"Path escapes knowledge base: {file_path}")

        return candidate
    
    async def _read_file(self, file_path: Path) -> str:
        try:
            async with aiofiles.open(file_path, 'r', encoding='utf-8') as f:
                return await f.read()
        except Exception as e:
            return f"Error reading file: {str(e)}"
    
    def list_files(self) -> Dict:
        def scan_dir(path: Path) -> Dict:
            result = {"type": "directory", "name": path.name, "children": []}
            
            if not path.exists():
                return result
            
            items = sorted(path.iterdir(), key=lambda x: (not x.is_dir(), x.name))
            
            for item in items:
                if item.name.startswith('.'):
                    continue
                
                if item.is_dir():
                    result["children"].append(scan_dir(item))
                else:
                    result["children"].append({
                        "type": "file",
                        "name": item.name,
                        "path": str(item.relative_to(self.base_path))
                    })
            
            return result
        
        return scan_dir(self.base_path)

knowledge_base = KnowledgeBase()
